site_name: "llm-runner"
theme:
  name: material
  features:
    - content.tabs.link
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_toc_entry: false
            show_category_heading: false
            toc_depth: 1
            members_order: source
            docstring_style: sphinx
  - mermaid2:
      version: 9.3.0
  - with-pdf
  - autorefs
  - mknotebooks:
      execute: false
markdown_extensions:
  - admonition
  - codehilite
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Tutorial:
     - 1. First program: tutorial/01-first-program
site_url: https://llm-runner.github.io/llm-runner/
repo_url: https://github.com/llm-runner/llm-runner/
